#!/bin/bash

# First test that OpenFOAM commands are available
which surfaceFeatureExtract &> /dev/null
retVal=$?
if [ $retVal -ne 0 ]; then
    echo "Could not find OpenFOAM command surfaceFeatureExtract, exiting. OpenFOAM v2312 is probably not sourced correctly?"
    exit 1
fi

rm -rf ? ?? ??? processor* constant/polyMesh
blockMesh
decomposePar

for i in `seq 1 1`; do
  mpirun -np 3 smoothMesh -parallel -layerExpansionRatio 1.2 -layerEdgeLength 0.05 -maxLayers 3 -layerPatches '(walls)' -smoothingPatches '(".*")'

  # mpirun -np 3 smoothMesh -parallel
done
