#!/bin/bash

cd "${0%/*}" || exit  # Run from the file location

# Stop at errors
set -e

# Check for OpenFOAM
if [[ -z "${WM_PROJECT}" ]]
then
    echo "Error: No OpenFOAM has been sourced. Stopping.."
    exit 1
else
    allowed_ver=("12" "v2412")
    if ! [[ " ${allowed_ver[*]} " == *" $WM_PROJECT_VERSION "* ]]; then
        echo "Warning: Version $WM_PROJECT_VERSION is not supported. Continuing.."
    fi
fi

# Deduce the OpenFOAM fork/variant in use
if [[ "$WM_PROJECT" == "foam" ]]; then
    echo "Sorry, foam is not currently supported! Stopping.."
    exit 1
else
    if [[ "$GFLAGS" == *"-DOPENFOAM="* ]]; then
        echo "Detected openfoam.com variant"
        export VERSION_SPECIFIC_INC="-DOPENFOAM_COM"
    elif [[ "$WM_PROJECT_VERSION" == *"v"* ]]; then
        echo "Detected openfoam.com variant"
        export VERSION_SPECIFIC_INC="-DOPENFOAM_COM"
    else
        echo "Assuming openfoam.org variant"
        export VERSION_SPECIFIC_INC="-DOPENFOAM_ORG"
    fi
fi

(cd src && wmake 2>&1 | tee log.Allwmake)

# Check if the build succeeded
echo "-----"
N_ERRORS_1=$(find . -name log.Allwmake | xargs grep " Error " | wc -l)
N_ERRORS_2=$(find . -name log.Allwmake | xargs grep " Stop." | wc -l)
if [[ $N_ERRORS_1 -gt 0 ]] || [[ $N_ERRORS_2 -gt 0 ]]
then
    echo "Following errors were found in the following logs:"
    echo $(find . -name log.Allwmake | xargs grep -l " Error ")
    echo $(find . -name log.Allwmake | xargs grep -l " Stop.")
    echo "Compilation of smoothMesh FAILED!"
    exit 1
else
    echo "Looks like compilation of smoothMesh succeeded!"
fi
