#!/bin/bash

# First test that OpenFOAM commands are available
which surfaceFeatureExtract &> /dev/null
retVal=$?
if [ $retVal -ne 0 ]; then
    echo "Could not find OpenFOAM command surfaceFeatureExtract, exiting. OpenFOAM v2312 is probably not sourced correctly?"
    exit 1
fi

rm -rf ? ?? ??? constant
extrude2DMesh MeshedSurface -overwrite
topoSet
createPatch -overwrite
cp -rv constant/polyMesh 0/

for i in `seq 1 100`; do
  smoothMesh -centroidalIters 1 -minEdgeLength 0.01 -maxStepLength 0.004 -minAngle 15 -maxAngle 160 -faceAngleConstraint true -boundaryMaxBlendingFraction 0.8 -boundaryEdgeLength 0.01 -patches '("def.*")'
done
