#!/bin/bash

# First test that OpenFOAM commands are available
which surfaceFeatureExtract &> /dev/null
retVal=$?
if [ $retVal -ne 0 ]; then
    echo "Could not find OpenFOAM command surfaceFeatureExtract, exiting. OpenFOAM is probably not sourced correctly?"
    exit 1
fi

rm -rf ? ?? ??? constant
extrude2DMesh MeshedSurface -overwrite
topoSet
createPatch -overwrite
cp -rv constant/polyMesh 0/

for i in `seq 1 1`; do
  smoothMesh -centroidalIters 100 -minEdgeLength 0.01 -maxStepLength 0.002 -minAngle 15 -maxAngle 160 -layerPatches '("def.*")'
done

# Test cases for illustration of wrong usage
# TODO: Update new parameter names

# No boundary layers, without faceAngleConstraint, produces self-intersections
# smoothMesh -centroidalIters 100 -minEdgeLength 0.01 -maxStepLength 0.004 -faceAngleConstraint false

# No boundary layers, too large minAngle does not allow much smoothing
# smoothMesh -centroidalIters 100 -minEdgeLength 0.01 -maxStepLength 0.004 -minAngle 45 -maxAngle 160 -faceAngleConstraint true

# No boundary layers, faceAngleConstraint creates mesh without self-intersections
# smoothMesh -centroidalIters 100 -minEdgeLength 0.01 -maxStepLength 0.004 -minAngle 15 -maxAngle 160 -faceAngleConstraint true

# Boundary layers without patches specification creates boundary layers on outer walls too
# smoothMesh -centroidalIters 100 -minEdgeLength 0.01 -maxStepLength 0.004 -minAngle 15 -maxAngle 160 -faceAngleConstraint true -boundaryMaxBlendingFraction 0.8 -boundaryEdgeLength 0.01

# Boundary layers for patch named default, best result
# smoothMesh -centroidalIters 100 -minEdgeLength 0.01 -maxStepLength 0.004 -minAngle 15 -maxAngle 160 -faceAngleConstraint true -boundaryMaxBlendingFraction 0.8 -boundaryEdgeLength 0.01 -patches '("def.*")'

# Boundary layers for patch named default, too large boundaryEdgeLength.
# smoothMesh -centroidalIters 100 -minEdgeLength 0.01 -maxStepLength 0.004 -minAngle 15 -maxAngle 160 -faceAngleConstraint true -boundaryMaxBlendingFraction 0.8 -boundaryEdgeLength 0.025 -patches '("def.*")'
