#!/bin/bash

# First test that OpenFOAM commands are available
which surfaceFeatureExtract &> /dev/null
retVal=$?
if [ $retVal -ne 0 ]; then
    echo "Could not find OpenFOAM command surfaceFeatureExtract, exiting. OpenFOAM v2312 is probably not sourced correctly?"
    exit 1
fi

rm -rf ? ?? ??? constant processor*
extrude2DMesh MeshedSurface -overwrite
topoSet
createPatch -overwrite
cp -rv constant/polyMesh 0/
decomposePar

for i in `seq 1 100`; do
  mpirun -np 3 smoothMesh -parallel -centroidalIters 1 -minEdgeLength 0.01 -maxStepLength 0.004 -minAngle 15 -maxAngle 160 -faceAngleConstraint true -boundaryMaxBlendingFraction 0.8 -boundaryEdgeLength 0.01 -patches '("def.*")'
done

# Test cases for illustration of wrong usage

# No boundary layers, without faceAngleConstraint, produces self-intersections
# mpirun -np 3 smoothMesh -parallel -centroidalIters 100 -minEdgeLength 0.01 -maxStepLength 0.004 -faceAngleConstraint false

# No boundary layers, too large minAngle does not allow much smoothing
# mpirun -np 3 smoothMesh -parallel -centroidalIters 100 -minEdgeLength 0.01 -maxStepLength 0.004 -minAngle 45 -maxAngle 160 -faceAngleConstraint true

# No boundary layers, faceAngleConstraint creates mesh without self-intersections
# mpirun -np 3 smoothMesh -parallel -centroidalIters 100 -minEdgeLength 0.01 -maxStepLength 0.004 -minAngle 15 -maxAngle 160 -faceAngleConstraint true

# Boundary layers without patches specification creates boundary layers on outer walls too
# mpirun -np 3 smoothMesh -parallel -centroidalIters 100 -minEdgeLength 0.01 -maxStepLength 0.004 -minAngle 15 -maxAngle 160 -faceAngleConstraint true -boundaryMaxBlendingFraction 0.8 -boundaryEdgeLength 0.01

# Boundary layers for patch named default, best result
# mpirun -np 3 smoothMesh -parallel -centroidalIters 100 -minEdgeLength 0.01 -maxStepLength 0.004 -minAngle 15 -maxAngle 160 -faceAngleConstraint true -boundaryMaxBlendingFraction 0.8 -boundaryEdgeLength 0.01 -patches '("def.*")'

# Boundary layers for patch named default, too large boundaryEdgeLength
# mpirun -np 3 smoothMesh -parallel -centroidalIters 100 -minEdgeLength 0.01 -maxStepLength 0.004 -minAngle 15 -maxAngle 160 -faceAngleConstraint true -boundaryMaxBlendingFraction 0.8 -boundaryEdgeLength 0.025 -patches '("def.*")'
