#!/bin/bash

# First test that OpenFOAM commands are available
which surfaceFeatureExtract &> /dev/null
retVal=$?
if [ $retVal -ne 0 ]; then
    echo "Could not find OpenFOAM command surfaceFeatureExtract, exiting. OpenFOAM is probably not sourced correctly?"
    exit 1
fi

rm -rf ? ?? ??? constant/polyMesh
extrudeMesh

mkdir 0
cp -rv constant/polyMesh 0/

for i in `seq 1 1`; do
  smoothMesh -layerPatches '(".*")' -writeInterval 1 -centroidalIters 50 -minLayers 2 -maxLayers 2 -layerMaxBlendingFraction 1.0 -edgeAngleConstraint false -faceAngleConstraint false -layerEdgeLength 0.05
done
