#!/bin/bash

# First test that OpenFOAM commands are available
which surfaceFeatureExtract &> /dev/null
retVal=$?
if [ $retVal -ne 0 ]; then
    echo "Could not find OpenFOAM command surfaceFeatureExtract, exiting. OpenFOAM is probably not sourced correctly?"
    exit 1
fi

rm -rf ? ?? ??? processor* constant/polyMesh
blockMesh
decomposePar

for i in `seq 1 1`; do
  mpirun -np 3 smoothMesh -parallel -relTol 1e-8 -centroidalIters 100 -minAngle 15 -maxLayers 3 -layerPatches '("wall.*")' -layerEdgeLength 0.005
done
