#!/bin/bash

# First test that OpenFOAM commands are available
which surfaceFeatureExtract &> /dev/null
retVal=$?
if [ $retVal -ne 0 ]; then
    echo "Could not find OpenFOAM command surfaceFeatureExtract, exiting. OpenFOAM is probably not sourced correctly?"
    exit 1
fi

rm -rf ? ?? ??? constant/polyMesh
blockMesh
mkdir 0
cp -rv constant/polyMesh 0/

for i in `seq 1 1`; do
  smoothMesh -relTol 1e-8 -centroidalIters 100 -minAngle 15 -writeInterval 50 -maxStepLength 0.0005 -maxLayers 3 -layerPatches '("wall.*")' -layerEdgeLength 0.0005
done
