#!/bin/bash

# First test that OpenFOAM commands are available
which surfaceFeatureExtract &> /dev/null
retVal=$?
if [ $retVal -ne 0 ]; then
    echo "Could not find OpenFOAM command surfaceFeatureExtract, exiting. OpenFOAM is probably not sourced correctly?"
    exit 1
fi

rm -rf ? ?? ??? constant/polyMesh processor*
blockMesh
mkdir -p 0/constant
cp -rv constant/polyMesh 0/constant/
decomposePar

for i in `seq 1 2`; do
  mpirun -np 3 smoothMesh -parallel -centroidalIters 50
done
